# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8761920d8fd5137789aa1887d370494bf97643212b06ae220f4eb51f19d12fd8f9ccf0ee281f383961425181043db67b2d7670618fdf8515f6e62163ab55a749

test:
  secret_key_base: 920b0346a0f0fa7857fe2a06a7713924b7bf6a9d2d17e32ac68e9a5bb098b2b1a55e856a5427318cf6d725a94e406a6a8802c7bbe6824886a72282eacf277727

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
